### ISSUE TITLE
annotations file?

### ISSUE THREAD

**Issue by reddevil1310** [wimlds-trojmiasto/detect-waste#47]
I dont know about annotations_epi.json
what and where is annotations_epi.json file?
Thank you very much

**Comment by majsylw** [comment]
Hi,
thank you for the question.
The annotation file which you mentioned is additional annotations provided by our partner epinote for unlabeled photos from TACO dataset. We did not release the part of annotations alone.
For whole extended TACO annotations with 7 classes look in https://github.com/wimlds-trojmiasto/detect-waste/tree/main/annotations. The photos can be downloaded from TACO repository.
Best,
Sylwia

**Comment by reddevil1310** [comment]
I want to start from scratch. When I run: python3 annotations_preprocessing.py, I need to ignore annotations_epi.json, don't I?
Thank you !

**Comment by majsylw** [comment]
To run the experiments from beining you have to have annotations per dataset in one file. In the scenario for TACO just combination of train and test files.
The main task of annotations_preprocessing.py or annotations_preprocessing_multi.py is to combine together annotations from few sources and make the classes consistent. Just convert to ours categories.
Keep in mind also that in splitting we have some randomnes, so you can create different train and test subsets.

**Comment by reddevil1310** [comment]
Thank you very much
