### ISSUE TITLE
TACO bboxes

### ISSUE THREAD

**Issue by gembancud** [wimlds-trojmiasto/detect-waste#49]
I wish to use TACO Bounding boxes as well for my project. Would you mind sharing the converted annotations?

**Comment by majsylw** [comment]
Hej, all annotations was provided in directory: https://github.com/wimlds-trojmiasto/detect-waste/tree/main/annotations
In short README.md you can find description about provided files.

**Comment by gembancud** [comment]
Looks like I overlooked this part. Thanks!
