### ISSUE TITLE
About clasifiy-waste dataset

### ISSUE THREAD

**Issue by XuanTr** [wimlds-trojmiasto/detect-waste#56]
Dear wimlds,
Thanks for your greate effort

I try the source code, but how to create classify-waste dataset.
I cant preproduce it now. Can you share me your classify-waste dataset for training

Thanks,
Xuan Tran

**Comment by majsylw** [comment]
Dear Xuan,
detailed statistics about images used in classification was provided in Table 2 (https://www.sciencedirect.com/science/article/pii/S0956053X21006474). You can download images from each subset at source websites. When it comes to object detected from OppenLittermap we provided annotations in https://github.com/wimlds-trojmiasto/detect-waste/blob/main/annotations/openlittermap.json
Best,
Sylwia Majchrowska

**Comment by XuanTr** [comment]
> Dear Xuan,

Dear Sylwia Majchrowska,

i have split dataset like articles. But for the current openlittermap data 
I have read that they don't let me download anymore, 
can you give me 55k images of that volume. I already built the classify-waste set, 
just missing the image from the openlittermap

Thanks,
Xuan Tran

**Comment by majsylw** [comment]
Unfortunately we cannot help you with that, becouse we do not have rights to share the data.
You should contact with OpenLitterMap owner.

**Comment by AgaMiko** [comment]
Hello Xuan,
As Sylwia explained we cannot share the images as the license terms changed. Now, the open litter map is pretty much closed. We tried contacting the owner but with no luck. 
However, I would like to add that the open litter map was used only for pseudo labeling, which did not significantly improve the results. You could try training without an open litter map dataset and should achieve similar results.
Good luck,
Agnieszka

**Comment by XuanTr** [comment]
> Hello Xuan, As Sylwia explained we cannot share the images as the license terms changed. Now, the open litter map is pretty much closed. We tried contacting the owner but with no luck. However, I would like to add that the open litter map was used only for pseudo labeling, which did not significantly improve the results. You could try training without an open litter map dataset and should achieve similar results. Good luck, Agnieszka

Dear SAgaMiko,
Thanks for your great effort on garbage research. I will try the way you said.
Thank you very much
