### ISSUE TITLE
How to use the data?

### ISSUE THREAD

**Issue by superfast852** [wimlds-trojmiasto/detect-waste#63]
Hello. I am building an object detector based on the YOLO family of models, and i would like to know how to use this dataset. 
Specifically the TACO box dataset annotations, but I'm confused on how to use it. Could you help me? Thanks!

**Comment by majsylw** [comment]
Hello, all annotations which we used are provided in the annotations directory: https://github.com/wimlds-trojmiasto/detect-waste/tree/main/annotations
Follow readme for detailed description. When it comes to the data itself, you need to download them from the sources, so the official webpages of data providers.

**Comment by AgaMiko** [comment]
> When it comes to the data itself, you need to download them from the sources, so the official webpages of data providers.

The links are also included in the readme: https://github.com/wimlds-trojmiasto/detect-waste#data-download-wip
