### ISSUE TITLE
classify-waste and Detect-waste

### ISSUE THREAD

**Issue by aliman80** [wimlds-trojmiasto/detect-waste#64]
Hi,
Thanks for your wonderful work in the domain. I have worked in underwater waste detection and now i want to use your dataset(waste-classify and waste detect)for my model. Can you guide me how and where to get these datasets.

Thanks again

**Comment by majsylw** [comment]
Hi,
The links for used datasets are included in the readme: https://github.com/wimlds-trojmiasto/detect-waste#data-download-wip
Annotations you can find in: the annotations directory: https://github.com/wimlds-trojmiasto/detect-waste/tree/main/annotations
