### ISSUE TITLE
Data Processing

### ISSUE THREAD

**Issue by kritikataank** [wimlds-trojmiasto/detect-waste#68]
Hi @AgaMiko, It would be really kind if you could help me through steps mentioned in the readme file, under Data Processing - Multiclass training; when I try to run python3 annotations_preprocessing.py I am facing this error: 
FileNotFoundError: [Errno 2] No such file or directory: '/dih4/dih4_2/wimlds/TACO-master/data/annotations.json'

**Comment by AgaMiko** [comment]
Hello,
the annotation description is available here: https://github.com/wimlds-trojmiasto/detect-waste/blob/main/annotations/README.md
Our annotations consist of:
- `annotations_train.json` and `annotations_test.json` for TACO dataset with 7 detect-waste categories object detection training,
- `annotations_binary_train.json` and `annotations_binary_test.json` for TACO dataset with 1 class object detection training,
- `binary_mixed_train.json` and `binary_mixed_train.json` for mixed dataset object detection training,
- `annotations_binary_mask_all_train.json` and `annotations_binary_mask_all_test.json` for mixed dataset instance segmentation training,
- and pseudoannotations (predictions from efficientdet) `openlittermap.json` for openlittermap dataset.
