### ISSUE TITLE
Want to know if detector model is provided

### ISSUE THREAD

**Issue by GloRiation** [wimlds-trojmiasto/detect-waste#73]
Hello, thank you for the great work. I am new learner of python, I am doing a bootcamp and want to use your project as demo. I installed the related packages and want to run the file make_predictions.py.  However, I am not sure what should I provide in the parameter --detector.

For the another similar parameter --classifier, I downloaded the .pth.tar file which you provided in Google Drive. I am not sure if it is correct as well.

Thanks for such a great work again. I learn a lot through your detailed documentation and It would be great if you can provide some helps to me. =)

**Comment by GloRiation** [comment]
I am sorry just found that the model you provided should be the detector model.

may I know where can I find the classifier model(I guess maybe something like efficientnet-b2.pth) such that I could run my make_predictions.

thanks a lot

**Comment by AgaMiko** [comment]
Hello,
We didn't upload the classifier model. You can try training it and sharing with the community though :)
Aga
