### ISSUE TITLE
https://detectwaste.ml/ offline

### ISSUE THREAD

**Issue by quinten-goens** [wimlds-trojmiasto/detect-waste#79]
I noted that https://detectwaste.ml/ is offline. The netlify app is still online https://detectwaste.netlify.app/. Did the domain name expire?

**Comment by AgaMiko** [comment]
Hello, yes.
The https://detectwaste.netlify.app/ is working and will be maintained.
Aga

**Comment by quinten-goens** [comment]
Super thanks for letting me know.
